name: carsbnb
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  google_fonts: ^6.2.1
  overlay_support: ^2.0.0  # <-- UPDATED
  google_maps_flutter: ^2.3.0
  cached_network_image: ^3.4.1
  webview_flutter: ^4.13.0
  flutter_svg: ^2.0.14
  equatable: ^2.0.5
  pinput: ^5.0.0
  sliver_tools: ^0.2.12
  expandable_page_view: ^1.0.17
  readmore: ^3.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  connectivity_plus: ^7.0.0
  dartz: ^0.10.1
  fluttertoast: ^9.0.0
  html: ^0.15.5
  timeago: ^3.7.0
  carousel_slider: ^5.0.0
  intl: ^0.20.2
  form_builder_validators: ^11.0.0
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  flutter_inappwebview: ^6.1.5
  flutter_widget_from_html_core: ^0.17.0
  awesome_snackbar_content: ^0.1.5
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/luncher_icon.png"
  min_sdk_android: 21
